src/objects/extRelListConfig__c.object
<CustomObject>
    <label>ExtRelList Config</label>
    <nameField>
        <displayFormat>EXTC-{0000000}</displayFormat>
        <label>ExtRelList Config Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>ExtRelList Configs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
    <fields>
        <fullName>listViewLabel__c</fullName>
        <label>ListView Label</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>sObjApiName__c</fullName>
        <label>sObjApiName</label>
        <length>255</length>
        <required>true</required>
        <type>Text</type>
    </fields>
</CustomObject>

xrl-core/main/default/objects/extRelListConfig__c/fields/ConfigType__c.field-meta.xml
<CustomField>
    <fullName>ConfigType__c</fullName>
    <label>ConfigType</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>XRL</fullName>
                <default>true</default>
                <label>XRL</label>
            </value>
            <value>
                <fullName>Tabular</fullName>
            </value>
            <value>
                <fullName>Layout</fullName>
            </value>
            <value>
                <fullName>Comparison</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

xrl-core/main/default/classes/getComparisonConfigs.cls
global with sharing class getComparisonConfigs extends VisualEditor.DynamicPickList{
    VisualEditor.DesignTimePageContext context;
    global getComparisonConfigs(VisualEditor.DesignTimePageContext context) {
        this.context = context;
    }
    global override VisualEditor.DataRow getDefaultValue() {
    VisualEditor.DataRow defaultValue = new VisualEditor.DataRow('red', 'RED');
    return defaultValue;
  }
    global override VisualEditor.DynamicPickListRows getValues() {
    List<extRelListConfig__c> allConfigs = [SELECT Id,name,sObjApiName__c,listViewLabel__c,ConfigType__c
        FROM extRelListConfig__c WHERE ConfigType__c = 'Comparison'];
    VisualEditor.DynamicPickListRows picklistValues = new VisualEditor.DynamicPickListRows();
    for (extRelListConfig__c configs: allConfigs) {
      picklistValues.addRow(
                new VisualEditor.DataRow(configs.ConfigType__c + ' - ' +configs.Name + ' - ' + configs.listViewLabel__c, (string)configs.Id + '::' + (string)configs.Name)
            );
    }
    return picklistValues;
  }
}